[package]
name = "rust-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"                               
bytes = "1.10.1"                              
thiserror = "2.0.17"                               
tokio = { version = "1.47.0", features = ["full"] }
